# Generated by Django 3.2.16 on 2022-11-24 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unit_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('rebate', models.FloatField(blank=True, null=True)),
                ('remain', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'payment_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'promotion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.employee')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('relationship', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'dependent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('order_no', models.ForeignKey(db_column='order_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.order')),
                ('item_no', models.IntegerField()),
                ('menu_code', models.CharField(max_length=50)),
                ('unit_price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('product_total', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'order_lineitem',
                'managed': False,
            },
        ),
    ]
